export const typeColors: Record<string, string> = {
   normal: 'var(--color-normal)',
   fighting: 'var(--color-fighting)',
   flying: 'var(--color-flying)',
   ground: 'var(--color-ground)',
   poison: 'var(--color-poison)',
   rock: 'var(--color-rock)',
   bug: 'var(--color-bug)',
   ghost: 'var(--color-ghost)',
   steel: 'var(--color-steel)',
   fire: 'var(--color-fire)',
   water: 'var(--color-water)',
   grass: 'var(--color-grass)',
   electric: 'var(--color-electric)',
   psychic: 'var(--color-psychic)',
   ice: 'var(--color-ice)',
   dragon: 'var(--color-dragon)',
   dark: 'var(--color-dark)',
   fairy: 'var(--color-fairy)',
};
